version: "3.9"
services:
  api:
    container_name: top-quotes-api
    image: cheojeg/top-quotes-api:1.0.6
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: [ "api" ]