// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Phrase struct {
	ID          int64        `json:"id"`
	Owner       string       `json:"owner"`
	State       string       `json:"state"`
	Phrase      string       `json:"phrase"`
	Author      string       `json:"author"`
	CreatedAt   time.Time    `json:"created_at"`
	PublishedAt sql.NullTime `json:"published_at"`
}

type PhraseState struct {
	State string `json:"state"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangerAt time.Time `json:"password_changer_at"`
	CreatedAt         time.Time `json:"created_at"`
}
