// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: phrase.sql

package db

import (
	"context"
	"time"
)

const countDraftPhrases = `-- name: CountDraftPhrases :one
SELECT COUNT(*)
FROM phrases
WHERE state = 'draft'
`

func (q *Queries) CountDraftPhrases(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDraftPhrases)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPhrasesPublishedToday = `-- name: CountPhrasesPublishedToday :one
SELECT COUNT(*)
FROM phrases
WHERE published_at::date = CURRENT_DATE
`

func (q *Queries) CountPhrasesPublishedToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPhrasesPublishedToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPhrase = `-- name: CreatePhrase :one
INSERT INTO phrases (
    owner, state, phrase, author, created_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, owner, state, phrase, author, created_at, published_at
`

type CreatePhraseParams struct {
	Owner     string    `json:"owner"`
	State     string    `json:"state"`
	Phrase    string    `json:"phrase"`
	Author    string    `json:"author"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreatePhrase(ctx context.Context, arg CreatePhraseParams) (Phrase, error) {
	row := q.db.QueryRowContext(ctx, createPhrase,
		arg.Owner,
		arg.State,
		arg.Phrase,
		arg.Author,
		arg.CreatedAt,
	)
	var i Phrase
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.State,
		&i.Phrase,
		&i.Author,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getPhraseByID = `-- name: GetPhraseByID :one
SELECT id, owner, state, phrase, author, created_at, published_at
FROM phrases
WHERE id = $1
`

func (q *Queries) GetPhraseByID(ctx context.Context, id int64) (Phrase, error) {
	row := q.db.QueryRowContext(ctx, getPhraseByID, id)
	var i Phrase
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.State,
		&i.Phrase,
		&i.Author,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getPhraseToPublish = `-- name: GetPhraseToPublish :one
SELECT id, owner, state, phrase, author, created_at, published_at
FROM phrases
WHERE state = 'published' AND published_at IS NULL OR published_at < NOW() - $1 * interval '1 days'
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) GetPhraseToPublish(ctx context.Context, dollar_1 interface{}) (Phrase, error) {
	row := q.db.QueryRowContext(ctx, getPhraseToPublish, dollar_1)
	var i Phrase
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.State,
		&i.Phrase,
		&i.Author,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getQuoteOfTheDay = `-- name: GetQuoteOfTheDay :one
SELECT id, owner, state, phrase, author, created_at, published_at
FROM phrases
WHERE state = 'published' AND published_at IS NOT NULL
ORDER BY published_at DESC
LIMIT 1
`

func (q *Queries) GetQuoteOfTheDay(ctx context.Context) (Phrase, error) {
	row := q.db.QueryRowContext(ctx, getQuoteOfTheDay)
	var i Phrase
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.State,
		&i.Phrase,
		&i.Author,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const listPhrases = `-- name: ListPhrases :many
SELECT id, owner, state, phrase, author, created_at, published_at
FROM phrases
LIMIT 20 OFFSET $1
`

func (q *Queries) ListPhrases(ctx context.Context, offset int32) ([]Phrase, error) {
	rows, err := q.db.QueryContext(ctx, listPhrases, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Phrase{}
	for rows.Next() {
		var i Phrase
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.State,
			&i.Phrase,
			&i.Author,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhrasesByState = `-- name: ListPhrasesByState :many
SELECT id, owner, state, phrase, author, created_at, published_at
FROM phrases
WHERE state = $1
`

func (q *Queries) ListPhrasesByState(ctx context.Context, state string) ([]Phrase, error) {
	rows, err := q.db.QueryContext(ctx, listPhrasesByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Phrase{}
	for rows.Next() {
		var i Phrase
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.State,
			&i.Phrase,
			&i.Author,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePhrase = `-- name: UpdatePhrase :one
UPDATE phrases
SET phrase = $2, author = $3
WHERE id = $1
RETURNING id, owner, state, phrase, author, created_at, published_at
`

type UpdatePhraseParams struct {
	ID     int64  `json:"id"`
	Phrase string `json:"phrase"`
	Author string `json:"author"`
}

func (q *Queries) UpdatePhrase(ctx context.Context, arg UpdatePhraseParams) (Phrase, error) {
	row := q.db.QueryRowContext(ctx, updatePhrase, arg.ID, arg.Phrase, arg.Author)
	var i Phrase
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.State,
		&i.Phrase,
		&i.Author,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const updatePhraseState = `-- name: UpdatePhraseState :one
UPDATE phrases
SET state = $2
WHERE id = $1
RETURNING id, owner, state, phrase, author, created_at, published_at
`

type UpdatePhraseStateParams struct {
	ID    int64  `json:"id"`
	State string `json:"state"`
}

func (q *Queries) UpdatePhraseState(ctx context.Context, arg UpdatePhraseStateParams) (Phrase, error) {
	row := q.db.QueryRowContext(ctx, updatePhraseState, arg.ID, arg.State)
	var i Phrase
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.State,
		&i.Phrase,
		&i.Author,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const updatePublishedAt = `-- name: UpdatePublishedAt :many
UPDATE phrases
SET published_at = NOW()
WHERE id = $1
RETURNING id, owner, state, phrase, author, created_at, published_at
`

func (q *Queries) UpdatePublishedAt(ctx context.Context, id int64) ([]Phrase, error) {
	rows, err := q.db.QueryContext(ctx, updatePublishedAt, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Phrase{}
	for rows.Next() {
		var i Phrase
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.State,
			&i.Phrase,
			&i.Author,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
