// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: phrase.sql

package db

import (
	"context"
	"time"
)

const createPhrase = `-- name: CreatePhrase :one
INSERT INTO phrases (
    owner, state, phrase, author, created_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, owner, state, phrase, author, created_at, published_at
`

type CreatePhraseParams struct {
	Owner     string    `json:"owner"`
	State     string    `json:"state"`
	Phrase    string    `json:"phrase"`
	Author    string    `json:"author"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreatePhrase(ctx context.Context, arg CreatePhraseParams) (Phrase, error) {
	row := q.db.QueryRowContext(ctx, createPhrase,
		arg.Owner,
		arg.State,
		arg.Phrase,
		arg.Author,
		arg.CreatedAt,
	)
	var i Phrase
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.State,
		&i.Phrase,
		&i.Author,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getPhraseToPublish = `-- name: GetPhraseToPublish :one
SELECT id, owner, state, phrase, author, created_at, published_at
FROM phrases
WHERE published_at IS NULL OR published_at < NOW() - INTERVAL $1 + ' days'
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) GetPhraseToPublish(ctx context.Context, dollar_1 int64) (Phrase, error) {
	row := q.db.QueryRowContext(ctx, getPhraseToPublish, dollar_1)
	var i Phrase
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.State,
		&i.Phrase,
		&i.Author,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const updatePhrase = `-- name: UpdatePhrase :one
UPDATE phrases
SET phrase = $2, author = $3
WHERE id = $1
RETURNING id, owner, state, phrase, author, created_at, published_at
`

type UpdatePhraseParams struct {
	ID     int64  `json:"id"`
	Phrase string `json:"phrase"`
	Author string `json:"author"`
}

func (q *Queries) UpdatePhrase(ctx context.Context, arg UpdatePhraseParams) (Phrase, error) {
	row := q.db.QueryRowContext(ctx, updatePhrase, arg.ID, arg.Phrase, arg.Author)
	var i Phrase
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.State,
		&i.Phrase,
		&i.Author,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const updatePhraseState = `-- name: UpdatePhraseState :one
UPDATE phrases
SET state = $2
WHERE id = $1
RETURNING id, owner, state, phrase, author, created_at, published_at
`

type UpdatePhraseStateParams struct {
	ID    int64  `json:"id"`
	State string `json:"state"`
}

func (q *Queries) UpdatePhraseState(ctx context.Context, arg UpdatePhraseStateParams) (Phrase, error) {
	row := q.db.QueryRowContext(ctx, updatePhraseState, arg.ID, arg.State)
	var i Phrase
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.State,
		&i.Phrase,
		&i.Author,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const updatePublishedAt = `-- name: UpdatePublishedAt :one
UPDATE phrases
SET published_at = NOW()
WHERE id = $1
RETURNING id, owner, state, phrase, author, created_at, published_at
`

func (q *Queries) UpdatePublishedAt(ctx context.Context, id int64) (Phrase, error) {
	row := q.db.QueryRowContext(ctx, updatePublishedAt, id)
	var i Phrase
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.State,
		&i.Phrase,
		&i.Author,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}
